### ISSUE TITLE
Helper method 'authenticate' does not work

### ISSUE THREAD

**Issue by schodevio** [rjurado01/rails_jwt_auth#77]
Hey, it seems that 'authenticate' method, without bang, does not work:

```ruby
module V2
  class TemplatesController < ApplicationController
    before_action :authenticate

    def index
      render json: Template.all.to_json, status: :ok
    end
  end
end


RSpec.describe V2::TemplatesController, type: :controller do
  describe '#index' do
    context 'when unauthorized' do
      it 'responds with error' do
        get :index

        expect(response).to have_http_status 401
      end
    end
  end
end
```

`RailsJwtAuth::AuthenticableHelper` included in ApplicationController
`RailsJwtAuth::Authenticatable` included in User model
`RailsJwtAuth::SpecHelpers` included in rspec_helper.rb

I expect to have 401 error response but I get 200 and json in response body. Did I forget something or that's a bug?

Besides that, `authenticate!` responds with odd errors:
1) No token provided:

```
JWT::DecodeError at /v2/templates
=================================

> Nil JSON web token

jwt (2.2.1) lib/jwt/decode.rb, line 12
--------------------------------------

    7   # JWT::Decode module
    8   module JWT
    9     # Decoding logic for JWT
   10     class Decode
   11       def initialize(jwt, key, verify, options, &keyfinder)
>  12         raise(JWT::DecodeError, 'Nil JSON web token') unless jwt
   13         @jwt = jwt
   14         @key = key
   15         @options = options
   16         @segments = jwt.split('.')
   17         @verify = verify

App backtrace
-------------

Full backtrace
--------------

 - jwt (2.2.1) lib/jwt/decode.rb:12:in `initialize'
 - jwt (2.2.1) lib/jwt.rb:28:in `decode'
 - rails_jwt_auth (1.5.0) lib/rails_jwt_auth/jwt_manager.rb:18:in `decode'
 - rails_jwt_auth (1.5.0) lib/rails_jwt_auth/jwt_manager.rb:30:in `decode_from_request'
 - rails_jwt_auth (1.5.0) app/controllers/concerns/rails_jwt_auth/authenticable_helper.rb:19:in `authenticate!'
```

2) Token has expired:

```
JWT::ExpiredSignature at /v2/templates
======================================

> Signature has expired

jwt (2.2.1) lib/jwt/verify.rb, line 41
--------------------------------------

   36         raise(JWT::InvalidAudError, "Invalid audience. Expected #{options_aud}, received #{aud || '<none>'}") if ([*aud] & [*options_aud]).empty?
   37       end
   38   
   39       def verify_expiration
   40         return unless @payload.include?('exp')
>  41         raise(JWT::ExpiredSignature, 'Signature has expired') if @payload['exp'].to_i <= (Time.now.to_i - exp_leeway)
   42       end
   43   
   44       def verify_iat
   45         return unless @payload.include?('iat')
   46   

App backtrace
-------------

Full backtrace
--------------

 - jwt (2.2.1) lib/jwt/verify.rb:41:in `verify_expiration'
 - jwt (2.2.1) lib/jwt/verify.rb:15:in `block (2 levels) in singleton class'
 - jwt (2.2.1) lib/jwt/verify.rb:22:in `block in verify_claims'
 - jwt (2.2.1) lib/jwt/verify.rb:20:in `verify_claims'
 - jwt (2.2.1) lib/jwt/decode.rb:64:in `verify_claims'
 - jwt (2.2.1) lib/jwt/decode.rb:27:in `decode_segments'
 - jwt (2.2.1) lib/jwt.rb:28:in `decode'
 - rails_jwt_auth (1.5.0) lib/rails_jwt_auth/jwt_manager.rb:18:in `decode'
 - rails_jwt_auth (1.5.0) lib/rails_jwt_auth/jwt_manager.rb:30:in `decode_from_request'
 - rails_jwt_auth (1.5.0) app/controllers/concerns/rails_jwt_auth/authenticable_helper.rb:19:in `authenticate!'
```

3. Invalid token:
```
JWT::DecodeError at /v2/templates
=================================

> Not enough or too many segments

jwt (2.2.1) lib/jwt/decode.rb, line 71
--------------------------------------

   66   
   67       def validate_segment_count!
   68         return if segment_length == 3
   69         return if !@verify && segment_length == 2 # If no verifying required, the signature is not needed
   70   
>  71         raise(JWT::DecodeError, 'Not enough or too many segments')
   72       end
   73   
   74       def segment_length
   75         @segments.count
   76       end

App backtrace
-------------

Full backtrace
--------------

 - jwt (2.2.1) lib/jwt/decode.rb:71:in `validate_segment_count!'
 - jwt (2.2.1) lib/jwt/decode.rb:23:in `decode_segments'
 - jwt (2.2.1) lib/jwt.rb:28:in `decode'
 - rails_jwt_auth (1.5.0) lib/rails_jwt_auth/jwt_manager.rb:18:in `decode'
 - rails_jwt_auth (1.5.0) lib/rails_jwt_auth/jwt_manager.rb:30:in `decode_from_request'
 - rails_jwt_auth (1.5.0) app/controllers/concerns/rails_jwt_auth/authenticable_helper.rb:19:in `authenticate!'
```

**Comment by rjurado01** [comment]
You should use `authenticate!` helper and it should raise `NotAuthorized` exception that you can rescue in your ApplicationController to return 401, for example:

```ruby
class ApplicationController < ActionController::API
  include RailsJwtAuth::AuthenticableHelper

  rescue_from RailsJwtAuth::NotAuthorized, with: :render_401
  ...
```

The `authenticate` method only try to load `@current_user`.

About errors, it seems an error with the `jwt` library: [jwt](https://github.com/jwt/ruby-jwt/blob/master/lib/jwt/decode.rb) which this gem uses. I'm going to investigate.

**Comment by rjurado01** [comment]
What version of the gem are you using?

When you use `authenticate!` without token, `JWT::DecodeError` exception should be rescued by `authenticate!` helper and converted into `NotAuthorized` as you can see [here](https://github.com/rjurado01/rails_jwt_auth/blob/master/app/controllers/concerns/rails_jwt_auth/authenticable_helper.rb#L20).

**Comment by schodevio** [comment]
According to attached backtrace: jwt (2.2.1) and rails_jwt_auth (1.5.0).

The good news is that problem dissapeared when I added rescue as you proposed:

```ruby
class ApplicationController < ActionController::Base
  include RailsJwtAuth::AuthenticableHelper

  rescue_from RailsJwtAuth::NotAuthorized, with: :unauthorized_response

  private

  def unauthorized_response
    head :unauthorized
  end
end
```
