### ISSUE TITLE
Testing raises uninitialized constant RailsJwtAuth::NotAuthorized

### ISSUE THREAD

**Issue by navimaia** [rjurado01/rails_jwt_auth#88]
I am trying to test my controllers, but it doesn't seem to work. Am I doing something incorrect?

With rspec, when I generate a controller spec, it actually generates a request spec. Not sure if this matters.

In `rails_helper.rb` I have included:
`require 'rails_jwt_auth/spec_helpers'`

as well as in the config block:
`config.include RailsJwtAuth::SpecHelpers, type: :controller`

Here's my controller spec code:
```
require 'rails_helper'

RSpec.describe "Certificates", type: :request do
  it 'blocks unauthenticated access' do
    expect { get '/v1/certificates/mine' }.to raise_error(RailsJwtAuth::NotAuthorized)
  end

  it 'allows authenticated access' do
    user = create(:user)
    sign_in user
    get '/v1/certificates/mine'
    expect(response).to be_success
  end
end
```

Here's the spec output:

```
Failures:

  1) Certificates blocks unauthenticated access
     Failure/Error: expect { get '/v1/certificates/mine' }.to raise_error(RailsJwtAuth::NotAuthorized)

     NameError:
       uninitialized constant RailsJwtAuth::NotAuthorized
     # ./spec/requests/certificates_request_spec.rb:5:in `block (2 levels) in <top (required)>'

  2) Certificates allows authenticated access
     Failure/Error: sign_in user

     NoMethodError:
       undefined method `sign_in' for #<RSpec::ExampleGroups::Certificates:0x00007fad582aaac8>
     # ./spec/requests/certificates_request_spec.rb:10:in `block (2 levels) in <top (required)>'

Finished in 0.3141 seconds (files took 1.1 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/requests/certificates_request_spec.rb:4 # Certificates blocks unauthenticated access
rspec ./spec/requests/certificates_request_spec.rb:8 # Certificates allows authenticated access
```

**Comment by navimaia** [comment]
I am able to get the specs to pass if I change the spec helpers type to :request
`config.include RailsJwtAuth::SpecHelpers, type: :request`

and alter the spec to be the following:
```
require 'rails_helper'

RSpec.describe "Certificates", type: :request do
  it 'blocks unauthenticated access' do
    expect { get '/v1/certificates/mine' }.to raise_error
  end

  it 'allows authenticated access' do
    user = create(:user)
    sign_in user
    get '/v1/certificates/mine'
    expect(response.status).to eq(200)
  end
end
```

However, I would like to test for the actual error, not just any error, as in your test code. Also, I'm not sure why testing the status code is different from `be_success`

**Comment by navimaia** [comment]
Okay, so I got it to work. 

1. I needed to add the name of my controller at the top instead of a string.
2. I needed to put it into the `spec/controllers` folder as rails_helper has this line: `config.infer_spec_type_from_file_location!`
3. My original :get route was incorrect and required a paramater.

Here is my final code:

```
require 'rails_helper'

RSpec.describe ::API::V1::CertificatesController, type: :controller do
  it 'blocks unauthenticated access' do
    expect { get :show, params: { id: 'mine' } }.to raise_error(RailsJwtAuth::NotAuthorized)
  end

  it 'allows authenticated access' do
    user = create(:user)
    sign_in user
    get :show, params: { id: 'mine' }
    expect(response.status).to eq(200)
  end
end
```

**Comment by rjurado01** [comment]
Great !!
